apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pipeline-one-run-
spec:
  pipelineRef:
    name: pipeline-one
  workspaces:
    - name: work
      emptyDir: {}    
  params:
  - name: task-one-param-1
    value: "value1"
  - name: task-two-param-1
    value: "value2"
  - name: pipeline-run-instance-name
    value: $(context.pipelineRun.name)