apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task-one
spec:
  params:
  - name: task-one-param-1
    description: task-one-param1
    type: string
  workspaces:
    - name: work
      # mountPath: /workspace
  steps:
  - name: task-one-step-1
    image: bash
    env:
    - name: RESULT_FILE_PATH
      value: "$(workspaces.work.path)/$(params.task-one-param-1)"    
    script: |
      #!/usr/bin/env bash
      echo "task-one-param-1: $(params.task-one-param-1)"
      echo "writing message Hello Nuwan! to file: $(params.task-one-param-1)"
      echo "Hello Nuwan!" > "${RESULT_FILE_PATH}"
      echo "sleeping 5 seconds..."
      sleep 5
      echo "exiting..."