apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task-one
spec:
  params:
  - name: task-one-param-1
    description: task-one-param1
    type: string
  workspaces:
    - name: work
      # mountPath: /workspace
  steps:
  - name: task-one-step-1
    image: bash
    script: |
      #!/usr/bin/env bash
      echo "task-one-step-1 running with task-one-param-1 $(params.task-one-param-1)"
      echo "sleeping 10 seconds..."
      echo "Hello Nuwan!" > "$(workspaces.work.path)/$(params.task-one-param-1)"    
      sleep 10
      echo "exiting..."    