apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task-two
spec:
  params:
  - name: task-two-param-1
    description: task-two-param1
    type: string
  workspaces:
    - name: work
      # mountPath: /workspace
  steps:
  - name: task-two-step-1
    image: bash
    script: |
      #!/usr/bin/env bash
      echo "task-two-param-1: $(params.task-two-param-1)"
      echo "exiting..."